### PR TITLE
Make the multiple-field_type visible and aligned correctly

### PR DESCRIPTION
**Pull request by bloveless**
It looks like there is too much padding at the front of the tags, but I didn't want to change it since every other input element has the same padding.

### CODE REVIEW

**Comment by RyanThompson** [comment]
A note on the theme - the bootstrap / flat-ui files will be 99% untouched. They only include variables from the theme for overriding the compiling.

The select.less should be added to theme components and modified there as an override. This way the styling rules merge from bootstrap, to flat ui, to the theme finally and each layer inherits its predecessor. 

Then if we want to update bootstrap we just replace the directory instead of untying all the changes n shit.

If this is usable let's leave it - I need to pull out the specific plugin UI to the field type anyways. Shouldn't be in the main theme - too opinionated.

**Comment by bloveless** [comment]
Okay. Let me give it another go.

**Comment by bloveless** [comment]
If I add a less directory and a less file to the field type will it be included automatically? Or is there something else that needs to be added to the field type? I did originally think that the specific css for the fields were self contained.

**Comment by RyanThompson** [comment]
Consider this: https://github.com/anomalylabs/boolean-field_type/blob/master/resources/views/input.twig#L1

**Comment by bloveless** [comment]
PERFECT!

**Comment by RyanThompson** [comment]
Also remember no need to add the less filter to the assets - picks it up from the extension

**Comment by bloveless** [comment]
I'm going to close this and move the changes to the multiple field type.

**Pull request closed without merging**
